version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

